name: Run Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  robot-tests:
    runs-on: windows-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      EMAIL_API: ${{ secrets.EMAIL_API }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PASSWORD_API: ${{ secrets.PASSWORD_API }}
      USERNAME: ${{ secrets.USERNAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          if exist requirements.txt (
            pip install -r requirements.txt
          ) else (
            echo "No requirements.txt found, skipping."
          )
          pip install --upgrade pip
          pip install robotframework
        shell: cmd

      - name: Run custom install script (if present)
        run: |
          if exist install-libraries.bat (
            .\install-libraries.bat
          ) else (
            echo "No install-libraries.bat found, skipping."
          )
        shell: cmd

      - name: Ensure results directory exists
        run: if not exist results mkdir results
        shell: cmd

      - name: Run Robot Framework tests
        run: |
          if not exist testsuites\reqres (
            echo "ERROR: Test suite directory 'testsuites\\reqres' not found!" && exit 1
          )
          robot --variable API_KEY:"%API_KEY%" ^
                --variable EMAIL_API:"%EMAIL_API%" ^
                --variable PASSWORD:"%PASSWORD%" ^
                --variable PASSWORD_API:"%PASSWORD_API%" ^
                --variable USERNAME:"%USERNAME%" ^
                --output results/output.xml ^
                --report results/report.html ^
                --log results/log.html ^
                testsuites/reqres
        shell: cmd

      - name: Upload Robot Framework report
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-report
          path: results/
